version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:143831952087:task-definition/policydriver-infractionservice-task:2"
        LoadBalancerInfo:
          ContainerName: "policy-driver-infraction-service"
          ContainerPort: "8085"
        PlatformVersion: "LATEST"